channels:
  - nodefaults
  - conda-forge
  
dependencies:
  - python>=3.9
  - pip
  - numpy
  - pydantic
  - pyyaml
  - tqdm
  - cupy
  - cuda-nvcc
# required for the CLI:
  - h5py
  - hdf5plugin
  - nibabel
  - pydicom
  - tifffile
  - scipy