channels:
  - nodefaults
  - conda-forge
  
dependencies:
  - python>=3.9
  - pip
  - numpy<2
  - scipy
  - pydantic
  - pyyaml
  - tqdm
  - cupy<13.3
  - cuda-version=12.2
  - h5py
  - hdf5plugin
  - nibabel
  - pydicom