channels:
  - nodefaults
  - conda-forge
  
dependencies:
  - python>=3.9
  - pip
  - numpy
  - scipy
  - pydantic
  - pyyaml
  - tqdm
  - cupy
  - cuda-nvcc
# required for the CLI:
  - h5py
  - hdf5plugin
  - nibabel
  - tifffile
# for videos:
  - imageio
  - imageio-ffmpeg
  - scikit-image