blank_issues_enabled: true
contact_links:
  - name: General Discussion
    url: https://github.com/danionella/warpfield/discussions
    about: For general questions, please visit our Discussions page.
  - name: Questions
    url: https://github.com/danionella/warpfield/discussions/categories/q-a
    about: For general questions, please visit our Q&A page.