# default recipe
pre_filter:
  clip_thresh: 0
  dog: true
  low: 0.5
  high: 10.0
levels:
  - block_size: [-4, -4, -4] # affine level. keep block size. Maybe adjust project low/high sigmas
    project:
      low: 2.0
      high: 10.0
    smooth:
      sigmas: [0.5, 0.5, 0.5]
    median_filter: false
    affinify: true
    repeat: 10
  - block_size: [64, 64, 64]
    project:
      low: 2.0
      high: 10.0
    smooth:
      sigmas: [2.0, 2.0, 2.0]
      long_range_ratio: 0.1
    repeat: 5
  - block_size: [32, 32, 32]
    block_stride: 0.5
    project:
      low: 1.0
      high: 2.0
    smooth:
      sigmas: [4.0, 4.0, 4.0]
      long_range_ratio: 0.1
    repeat: 5